# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import battleship_pb2 as battleship__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in battleship_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BattleShipServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createMessage = channel.unary_unary(
                '/battleship.BattleShipService/createMessage',
                request_serializer=battleship__pb2.CreateRequest.SerializeToString,
                response_deserializer=battleship__pb2.CreateReply.FromString,
                _registered_method=True)
        self.joinMessage = channel.unary_unary(
                '/battleship.BattleShipService/joinMessage',
                request_serializer=battleship__pb2.JoinRequest.SerializeToString,
                response_deserializer=battleship__pb2.JoinReply.FromString,
                _registered_method=True)


class BattleShipServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def joinMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BattleShipServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.createMessage,
                    request_deserializer=battleship__pb2.CreateRequest.FromString,
                    response_serializer=battleship__pb2.CreateReply.SerializeToString,
            ),
            'joinMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.joinMessage,
                    request_deserializer=battleship__pb2.JoinRequest.FromString,
                    response_serializer=battleship__pb2.JoinReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'battleship.BattleShipService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('battleship.BattleShipService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BattleShipService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/battleship.BattleShipService/createMessage',
            battleship__pb2.CreateRequest.SerializeToString,
            battleship__pb2.CreateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def joinMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/battleship.BattleShipService/joinMessage',
            battleship__pb2.JoinRequest.SerializeToString,
            battleship__pb2.JoinReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
